### PR TITLE
Add HiFive1 board support

### PR DESCRIPTION
**Pull request by MichaelZaidman**
The HiFive1 is the first Arduino-compatible RISC-V based board built with FE310
CPU from SiFive. The board is about 20 times faster than Arduino UNO.

Additional info:
The board - https://www.sifive.com/boards/hifive1
The Arduino code - https://github.com/westerndigitalcorporation/cinco
The HiFive1 package for Arduino IDE - https://github.com/westerndigitalcorporation/CincoWinPkg

Adding HiFive1 support to the library.

Signed-off-by: Michael Zaidman <Michael.Zaidman@wdc.com>

### CODE REVIEW

**Comment by MichaelZaidman** [comment]
A close look into the [travis-ci report](https://travis-ci.com/adafruit/Adafruit-Fingerprint-Sensor-Library/builds/98149301) shows that the build failed for M4 platform. But the code in the master branch is also failing when compiled for Adafruit M4 Metro board since it cannot find the SoftwareSerial library which seems isn't implemented for this platform...

**Comment by ladyada** [comment]
thats because you removed these lines

#if defined(__AVR__) || defined(ESP8266)
    #include <SoftwareSerial.h>
#endif

**Comment by MichaelZaidman** [comment]
As I wrote earlier, the original code in master branch (without my changes) also failed to compile for M4.

I removed the include of the SoftwareSerial.h from the fingerprint.cpp file since it's already included in the fingerprint.h file which is also included in the fingerprint.cpp. So no need to include it twice.

**Comment by ladyada** [comment]
ooh i see! ok could you add a .m4.test.skip file to those directories? we must have added the M4 test after our last sweep of this lirbary. that would help us a ton and then we'd merge this all in togehter :)

**Comment by ladyada** [comment]
aaaahmazing!

**Pull request merged**
