### PR TITLE
Fixed typo in setBaudRate method

### PR DESCRIPTION
**Pull request by frami**
There was a typo in the setBaudRate method. For that reason, it was not possible to change the baudrate.

### CODE REVIEW

**Comment by Varocol** [comment]
It seems that the author confused the class variables with the incoming parameters, but unfortunately I didn't see it until I came to look for an issue on this method. I hope the author can merge this submission in the next version as soon as possible. By the way, I hope that the compatibility with softwareserial is not limited to the platform given by the macro definition, because I'm using the esp32 platform and then tossed around for an evening to find that the platform is incompatible. So I added defined (ESP32) manually (all from the translator)

**Comment by capedra** [comment]
@ladyada 
@evaherrada 
@frami 
Could anyone please merge this pull request? Because here we are, about a year has already passed, and all I'm getting as the return of the command "finger.setBaudRate(FINGERPRINT_BAUDRATE_115200);" is the code 1, which is an error.
Thanks !!

**Comment by capedra** [comment]
Also, whenever I change the baud rate of the fingerprint sensor to 115200 and I run the command ```finger.getParameters()```, I always get the value ```49664``` for ```finger.baud_rate``` attribute, probably because ```baud_rate``` has the type of ```uint16_t``` in the library.

**Review by ladyada — APPROVED** [review]

**Comment by ladyada** [comment]
yes this does fix the typo, merged!

**Pull request merged**
