### PR TITLE
Added password support

### PR DESCRIPTION
**Pull request by RoelVB**
Added the possibility to set and use the password for some extra security

### CODE REVIEW

**Comment by androstorm** [comment]
hello your library for fingerprint it is possible to add passwordchange.ino example to change the fingerprint password factory default.
thank you in advance
andro

**Comment by RoelVB** [comment]
@androstorm I've added an example. I was unable to test it, but it should be fine.

**Comment by androstorm** [comment]
great job thank you  for the example of 
changepassword.ino.

and it possible to do the same thing for the serial default?
changeserial.ino


thank you in advance
andro

**Comment by RoelVB** [comment]
If you want to use the hardware serial to communicate with the fingerprint sensor your should change `Adafruit_Fingerprint(&mySerial)` to `Adafruit_Fingerprint(&Serial)` and your should remove the hardware serial debug messages.

**Comment by androstorm** [comment]
changepassword.ino work correctly  
thank you   
//finger.begin(19200);  replaced in finger.begin(57600);
my email androstorm@gmail.com

**Comment by ladyada** [comment]
hiya we've kinda redone the whole library - you may want to re-base :)

**Comment by RoelVB** [comment]
Well... there are no more merge conflict anymore, but I did something wrong trying to rebase.
Maybe I should just delete my repository and try again?

Good to see this library gets some attention.

**Comment by ladyada** [comment]
lol yeah we changed a lot - but it also works a lot better now :).
if you dont mind, a re-do would be appreciated. we're doing a bunch of work on this so we'd merge it fast!

**Comment by RoelVB** [comment]
Created a new and clean pull request #32

**Pull request closed without merging**
