### PR TITLE
Fixes issue #66: Broken link in README

### PR DESCRIPTION
**Pull request by froexilize**
Also need to change website link in repo description.

### CODE REVIEW

**Comment by froexilize** [comment]
It is strange things... I can access product page only from Tor-browser. Double check please what's going wrong. My location is in Russia.

**Comment by froexilize** [comment]
image

**Comment by froexilize** [comment]
image

**Comment by ladyada** [comment]
hiya cloudflare may be blocking your IP - the link definitely works :)

**Pull request closed without merging**
